version: "3.8"
services:
  postgres:
    container_name: postgres
    image: postgres:15.3-alpine3.17
    environment:
      - POSTGRES_USER=easylearnz
      - POSTGRES_PASSWORD=easylearnz
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - microservice_postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.5
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
volumes:
  microservice_postgres_data:
  pgadmin:
